# **Cellphone Problem**

## **Problem Statement**
![cellphone-problem](Cellphone-Problem.jpeg)

In [11]:

#Prior Belief -> person is at some location
probPrior <- matrix(c(0.05,0.10,0.05,0.05,0.05,0.10,0.05,0.05,0.05,0.05,0.10,0.05,0.05,0.05,0.10,0.05), nrow = 4, ncol = 4, byrow = TRUE)
print(probPrior)

#Probability that you observe two bars of signal given your are in a specific loacation

prob2Bar <- matrix(c(0.75,0.95,0.75,0.05,0.05,0.75,0.95,0.75,0.01,0.05,0.75,0.95,0.01,0.01,0.05,0.75), nrow = 4, ncol = 4, byrow = TRUE)

print(prob2Bar)

#Person is at some loaction given that he observes 2 bars of signal

#Applying Bayes theorem and law of total probability
result <- (prob2Bar * probPrior)/sum(prob2Bar*probPrior)

print(result)



     [,1] [,2] [,3] [,4]
[1,] 0.05 0.10 0.05 0.05
[2,] 0.05 0.10 0.05 0.05
[3,] 0.05 0.05 0.10 0.05
[4,] 0.05 0.05 0.10 0.05
     [,1] [,2] [,3] [,4]
[1,] 0.75 0.95 0.75 0.05
[2,] 0.05 0.75 0.95 0.75
[3,] 0.01 0.05 0.75 0.95
[4,] 0.01 0.01 0.05 0.75
             [,1]         [,2]        [,3]        [,4]
[1,] 0.0744047619 0.1884920635 0.074404762 0.004960317
[2,] 0.0049603175 0.1488095238 0.094246032 0.074404762
[3,] 0.0009920635 0.0049603175 0.148809524 0.094246032
[4,] 0.0009920635 0.0009920635 0.009920635 0.074404762
